version: '3.2'
services:
  # --------------------------------
  addition:
    container_name: addition
    image: scherbina/calc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - default
    dns: 172.25.1.30
    ports:
    - "8080:8080"
    restart: always
    command: >
      add
  # --------------------------------
  subtraction:
    container_name: subtraction
    image: scherbina/calc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - default
    ports:
    - "8081:8080"
    restart: always
    command: >
      sub
  # --------------------------------
  multiplication:
    container_name: multiplication
    image: scherbina/calc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - default
    ports:
    - "8082:8080"
    restart: always
    command: >
      mul
  # --------------------------------
  division:
    container_name: division
    image: scherbina/calc
    build:
      context: .
      dockerfile: Dockerfile
    networks:
    - default
    ports:
    - "8083:8080"
    restart: always
    command: >
      div

volumes:
  rpc:
    driver: local

networks:
  default:
    ipam:
      driver: default
      config:
      - subnet: 172.25.0.1/16